fixed the ci.yml file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,5 +21,5 @@ jobs:
       - name: Test api
         run: go test ./...
 
-      - name: Failure case
-        run: (exit 1)
+      #- name: Failure case
+      #  run: (exit 1)
